/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : TWAIN
 #	author : miyako
 #	2017/11/27
 #
 # --------------------------------------------------------------------------------*/

#define JPEG_DEFAULT_RESOLUTION 300
#define PNG_DEFAULT_RESOLUTION JPEG_DEFAULT_RESOLUTION

#define TWAIN_PROCESS_EVENT_TIMEOUT 30

#define TWAIN_SIGNAL_PREFIX L"TWAIN_4D"

#define INCHES_PER_METER (100.0/2.54)

#define PNG_COLOR_TYPE_UNKNOWN -1

#if VERSIONWIN
#include <process.h>  
#define USE_TWAIN_DSM 1
#define _false FALSE
#define _true TRUE
#else
#define USE_TWAIN_DSM 0
#endif

#if USE_TWAIN_DSM
#include "dsm.h"
#else
#if VERSIONMAC
#include <TWAIN/TWAIN.h>
#define SSTRCPY(d,z,s) strlcpy((char *)d,(const char *)s,(size_t)z)
#define SSTRCAT(d,z,s) strcat(d,s)
#define SSTRNCPY(d,z,s,m) strncpy(d,s,m)
#define SGETENV(d,z,n) strcpy(d,getenv(n)?getenv(n):"")
typedef void* HWND;
#endif
#endif

#define PRODUCT_VENDOR_NAME "4D"
#define PRODUCT_FAMILY_NAME "4D"
#define PRODUCT_NAME "4D"

#define CMD_Get_database_localization 1009

#include "libjson.h"
#include "png.h"
#include "jpeglib.h"

// --- TWAIN
void TWAIN_SCANNERS_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void TWAIN_Get_default_option(sLONG_PTR *pResult, PackagePtr pParams);
void TWAIN_SCAN(sLONG_PTR *pResult, PackagePtr pParams);

#define CAP_VALUE_BUF_SIZE 1024

#if VERSIONWIN
unsigned __stdcall doScanWin(void *p);
#endif
void doScan(C_TEXT &Param1_scanner, JSONNODE *Param2_option, int Param3_format, C_BLOB& picture);

